In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr+10)

matrix = np.array([[1, 2], [3, 4]])
print(matrix.T)

[11 12 13 14 15]
[[1 3]
 [2 4]]


In [10]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
seq_1 = np.arange(0, 10, 2)
print(seq_1)

[0 2 4 6 8]


In [19]:
linspace = np.linspace(0, 10, 5)
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


In [4]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

<class 'numpy.ndarray'>
(3, 3)
2
9
int64


In [8]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[:])
print(arr[1:4])
print(arr[:4])
print(arr[1:])

[10 20 30 40 50]
[20 30 40]
[10 20 30 40]
[20 30 40 50]


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr[:2,1:])
print(arr[1:,:2])

[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [18]:
print(arr1+arr2)
print(arr1+10)

[5 7 9]
[11 12 13]


In [19]:
arr = np.array([1,2,3,4,5,6])

In [21]:
reshape = arr.reshape(2,3)
print(reshape)

[[1 2 3]
 [4 5 6]]


In [23]:
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [25]:
arr = np.array([1,2,3,4,5,6])
filter_arr = arr[arr > 3]
print(filter_arr)

[4 5 6]


In [28]:
ran_val = np.random.rand(5)
print(ran_val)

[0.45816183 0.99796289 0.50368486 0.90356325 0.53181145]


In [36]:
ran_int = np.random.randint(1, 45, size=(5,6))
print(ran_int)

[[44 39 31 29 19 20]
 [22 37 12 38  9 44]
 [17 39 37 38 29  5]
 [29 19 40 19 31 30]
 [ 4 23 28 17  7 19]]
